# Generated by Django 4.1.3 on 2022-12-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, help_text='only svg file!', null=True, upload_to='categories/'),
        ),
    ]
