# Generated by Django 4.1.3 on 2022-12-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app_shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SlugField(choices=[('limited', 'Ограниченный тираж'), ('top', 'Топ продаж'), ('sale', 'Распродажа'), ('default', 'Стандарт')], default='default', max_length=10, verbose_name='статус'),
        ),
    ]
