# Generated by Django 4.1.3 on 2022-12-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_alter_product_category_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='super_category',
            new_name='parent',
        ),
    ]
