# Generated by Django 4.1.3 on 2022-12-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_rename_super_category_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.BooleanField(default=False, verbose_name='является родительской'),
        ),
    ]
