# Generated by Django 4.2.7 on 2023-11-15 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='название')),
                ('slug', models.SlugField(max_length=10, verbose_name='url')),
                ('favorites', models.BooleanField(default=False, verbose_name='избранное')),
                ('icon', models.FileField(blank=True, help_text='.svg', null=True, upload_to='categories/', verbose_name='иконка')),
                ('changed_in', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_store.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CostOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_simple', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='стоимость простой доставки')),
                ('free_limit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='бесплатно от')),
                ('price_express', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='стоимость экспресс доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата заказа')),
                ('paid', models.BooleanField(default=False, verbose_name='оплачен')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена')),
                ('status', models.CharField(choices=[('top', 'топ продаж'), ('limit_ed', 'ограниченное издание'), ('default', 'простой')], default='default', max_length=10, verbose_name='статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата первого поступления')),
                ('description', models.TextField(max_length=5000, verbose_name='описание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_store.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_product', models.PositiveIntegerField(default=0, verbose_name='количество товара')),
                ('price_of_product', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='app_store.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='app_store.Purchase', to='app_store.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, verbose_name='город')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('delivery_type', models.CharField(choices=[('simple', 'простая'), ('express', 'экспресс')], default='simple', max_length=10, verbose_name='тип доставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='стоимость доставки')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_store.order')),
            ],
        ),
    ]
