# Generated by Django 4.2.7 on 2023-11-25 09:00

import app_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_store', '0002_alter_category_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата создания / изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('fio', models.CharField(blank=True, max_length=50, verbose_name='Ф.И.О.')),
                ('avatar', models.ImageField(blank=True, upload_to=app_user.models.get_user_dir, verbose_name='аватар')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='город')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='адрес')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='создан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'db_table': 'profiles',
            },
        ),
    ]
